import { extractVideoId } from '@clipscribe/shared'
import type { TranscriptProvider, TranscriptResult } from './transcript-provider'
import { config } from '../config'
import { AppError } from '../lib/errors'
import { plainTextToSrt, plainTextToVtt } from './transcript'

/** 通过 Piped 代理拉字幕，绕过 Render IP 对 youtube.com 的直接限流 */
const PIPED_INSTANCES = [
  'https://pipedapi.kavin.rocks',
  'https://pipedapi.adminforge.de',
  'https://api.piped.yt',
  'https://pipedapi.leptons.xyz',
  'https://pipedapi.in.projectsegfau.lt',
]

interface PipedSubtitle {
  url?: string
  code?: string
  name?: string
  autoGenerated?: boolean
}

interface PipedStreamResponse {
  title?: string
  subtitles?: PipedSubtitle[]
}

function pickSubtitle(subs: PipedSubtitle[]): PipedSubtitle | null {
  if (!subs.length)
    return null
  const preferZh = config.subtitleLang === 'zh'
  const score = (s: PipedSubtitle): number => {
    const code = (s.code || '').toLowerCase()
    const manual = s.autoGenerated ? 0 : 4
    if (preferZh) {
      if (code.startsWith('zh'))
        return 10 + manual
      if (code === 'en')
        return 5 + manual
    }
    else {
      if (code === 'en')
        return 10 + manual
      if (code.startsWith('zh'))
        return 5 + manual
    }
    return manual
  }
  return [...subs].sort((a, b) => score(b) - score(a))[0] ?? null
}

function xmlTranscriptToPlain(xml: string): string {
  const lines: string[] = []
  const re = /<text[^>]*>([\s\S]*?)<\/text>/gi
  let m: RegExpExecArray | null
  while ((m = re.exec(xml)) !== null) {
    const text = m[1]
      .replace(/<[^>]+>/g, '')
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, '\'')
      .replace(/\n/g, ' ')
      .trim()
    if (text)
      lines.push(text)
  }
  return lines.filter((line, i, arr) => line !== arr[i - 1]).join('\n')
}

function subtitleBodyToPlain(body: string): string {
  if (/^WEBVTT/m.test(body)) {
    return body
      .replace(/^WEBVTT.*$/gm, '')
      .replace(/\d{2}:\d{2}:\d{2}\.\d{3}\s*-->\s*\d{2}:\d{2}:\d{2}\.\d{3}/g, '')
      .replace(/<[^>]+>/g, '')
      .split('\n')
      .map(l => l.trim())
      .filter(Boolean)
      .filter((line, i, arr) => line !== arr[i - 1])
      .join('\n')
  }
  if (/<text[\s>]/i.test(body))
    return xmlTranscriptToPlain(body)
  return body.trim()
}

async function fetchJson(url: string, timeoutMs: number): Promise<unknown | null> {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  try {
    const res = await fetch(url, {
      signal: controller.signal,
      headers: { Accept: 'application/json' },
    })
    if (!res.ok)
      return null
    return await res.json()
  }
  catch {
    return null
  }
  finally {
    clearTimeout(timer)
  }
}

async function fetchSubtitleText(url: string, timeoutMs: number): Promise<string | null> {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  try {
    const res = await fetch(url, { signal: controller.signal })
    if (!res.ok)
      return null
    return await res.text()
  }
  catch {
    return null
  }
  finally {
    clearTimeout(timer)
  }
}

export class PipedCaptionsProvider implements TranscriptProvider {
  readonly name = 'piped'

  async fetch(url: string, _workDir: string): Promise<TranscriptResult> {
    const videoId = extractVideoId(url)
    if (!videoId)
      throw new AppError('无效的 YouTube 链接', 400, 'INVALID_URL')

    const timeout = config.youtubePageTimeoutMs
    let lastError = 'Piped 实例不可用'

    for (const base of PIPED_INSTANCES) {
      const data = await fetchJson(`${base}/streams/${videoId}`, timeout) as PipedStreamResponse | null
      if (!data?.subtitles?.length)
        continue

      const sub = pickSubtitle(data.subtitles)
      if (!sub?.url) {
        lastError = '无匹配语言字幕'
        continue
      }

      const raw = await fetchSubtitleText(sub.url, config.youtubeCaptionTimeoutMs)
      if (!raw?.trim()) {
        lastError = '字幕下载失败'
        continue
      }

      const plain = subtitleBodyToPlain(raw)
      if (!plain.trim()) {
        lastError = '字幕内容为空'
        continue
      }

      const title = data.title?.trim() || 'YouTube Video'
      const vtt = /^WEBVTT/m.test(raw) ? raw : plainTextToVtt(plain)
      const srt = plainTextToSrt(plain)
      return {
        videoTitle: title,
        transcript: plain,
        formats: { txt: plain, srt, vtt },
      }
    }

    throw new AppError(lastError, 502, 'YTDLP_FAILED')
  }
}

export const pipedCaptionsProvider = new PipedCaptionsProvider()
