import { extractVideoId } from './youtube'
import { buildTranscriptFormats, subtitleBodyToPlain } from './subtitle-text'

export interface ProxyTranscriptResult {
  videoTitle: string
  transcript: string
  formats: { txt: string, srt: string, vtt: string }
}

const PIPED_INSTANCES = [
  'https://pipedapi.kavin.rocks',
  'https://pipedapi.adminforge.de',
  'https://api.piped.yt',
  'https://pipedapi.leptons.xyz',
  'https://pipedapi.in.projectsegfau.lt',
]

const INVIDIOUS_INSTANCES = [
  'https://invidious.fdn.fr',
  'https://inv.nadeko.net',
  'https://yewtu.be',
  'https://invidious.nerdvpn.de',
  'https://invidious.private.coffee',
]

export interface ProxyFetchOptions {
  preferZh?: boolean
  pageTimeoutMs?: number
  captionTimeoutMs?: number
}

async function fetchText(url: string, timeoutMs: number): Promise<string | null> {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  try {
    const res = await fetch(url, { signal: controller.signal })
    if (!res.ok)
      return null
    return await res.text()
  }
  catch {
    return null
  }
  finally {
    clearTimeout(timer)
  }
}

async function fetchJson(url: string, timeoutMs: number): Promise<unknown | null> {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  try {
    const res = await fetch(url, {
      signal: controller.signal,
      headers: { Accept: 'application/json' },
    })
    if (!res.ok)
      return null
    return await res.json()
  }
  catch {
    return null
  }
  finally {
    clearTimeout(timer)
  }
}

function langScore(code: string, preferZh: boolean, manual: boolean): number {
  const c = code.toLowerCase()
  const m = manual ? 4 : 0
  if (preferZh) {
    if (c.startsWith('zh') || c.includes('chinese'))
      return 10 + m
    if (c === 'en' || c.includes('english'))
      return 5 + m
  }
  else {
    if (c === 'en' || c.includes('english'))
      return 10 + m
    if (c.startsWith('zh') || c.includes('chinese'))
      return 5 + m
  }
  return m
}

async function tryPiped(
  videoId: string,
  opts: ProxyFetchOptions,
): Promise<ProxyTranscriptResult | null> {
  const pageMs = opts.pageTimeoutMs ?? 25_000
  const capMs = opts.captionTimeoutMs ?? 30_000
  const preferZh = opts.preferZh ?? true

  for (const base of PIPED_INSTANCES) {
    const data = await fetchJson(`${base}/streams/${videoId}`, pageMs) as {
      title?: string
      subtitles?: Array<{ url?: string, code?: string, autoGenerated?: boolean }>
    } | null
    if (!data?.subtitles?.length)
      continue

    const sub = [...data.subtitles].sort((a, b) => {
      const sa = langScore(a.code || '', preferZh, !a.autoGenerated)
      const sb = langScore(b.code || '', preferZh, !b.autoGenerated)
      return sb - sa
    })[0]
    if (!sub?.url)
      continue

    const raw = await fetchText(sub.url, capMs)
    if (!raw)
      continue
    const plain = subtitleBodyToPlain(raw)
    if (!plain.trim())
      continue

    return {
      videoTitle: data.title?.trim() || 'YouTube Video',
      transcript: plain,
      formats: buildTranscriptFormats(plain),
    }
  }
  return null
}

async function tryInvidious(
  videoId: string,
  opts: ProxyFetchOptions,
): Promise<ProxyTranscriptResult | null> {
  const pageMs = opts.pageTimeoutMs ?? 25_000
  const capMs = opts.captionTimeoutMs ?? 30_000
  const preferZh = opts.preferZh ?? true

  for (const base of INVIDIOUS_INSTANCES) {
    const listRaw = await fetchText(`${base}/api/v1/captions/${videoId}`, pageMs)
    if (!listRaw)
      continue
    let list: Array<{ label: string, language_code?: string, languageCode?: string }>
    try {
      list = JSON.parse(listRaw) as typeof list
    }
    catch {
      continue
    }
    if (!Array.isArray(list) || !list.length)
      continue

    const meta = [...list].sort((a, b) => {
      const ca = a.language_code || a.languageCode || a.label
      const cb = b.language_code || b.languageCode || b.label
      return langScore(cb, preferZh, true) - langScore(ca, preferZh, true)
    })[0]
    if (!meta?.label)
      continue

    const subRaw = await fetchText(
      `${base}/api/v1/captions/${videoId}?label=${encodeURIComponent(meta.label)}`,
      capMs,
    )
    if (!subRaw)
      continue
    const plain = subtitleBodyToPlain(subRaw)
    if (!plain.trim())
      continue

    let title = 'YouTube Video'
    const videoRaw = await fetchText(`${base}/api/v1/videos/${videoId}`, pageMs)
    if (videoRaw) {
      try {
        const v = JSON.parse(videoRaw) as { title?: string }
        if (v.title?.trim())
          title = v.title.trim()
      }
      catch { /* ignore */ }
    }

    return {
      videoTitle: title,
      transcript: plain,
      formats: buildTranscriptFormats(plain),
    }
  }
  return null
}

/** 通过 Piped / Invidious 拉字幕（适合浏览器与服务器，不直连 youtube.com） */
export async function fetchTranscriptViaProxies(
  url: string,
  opts: ProxyFetchOptions = {},
): Promise<ProxyTranscriptResult | null> {
  const videoId = extractVideoId(url)
  if (!videoId)
    return null
  return (await tryPiped(videoId, opts)) ?? (await tryInvidious(videoId, opts))
}
