import { extractVideoId } from './youtube'
import { buildTranscriptFormats, subtitleBodyToPlain } from './subtitle-text'

export interface ProxyTranscriptResult {
  videoTitle: string
  transcript: string
  formats: { txt: string, srt: string, vtt: string }
}

const PIPED_INSTANCES = [
  'https://pipedapi.adminforge.de',
  'https://api.piped.yt',
  'https://pipedapi.leptons.xyz',
  'https://pipedapi.in.projectsegfau.lt',
  'https://pipedapi.kavin.rocks',
]

const INVIDIOUS_INSTANCES = [
  'https://invidious.fdn.fr',
  'https://inv.nadeko.net',
  'https://yewtu.be',
  'https://invidious.private.coffee',
  'https://invidious.nerdvpn.de',
]

export interface ProxyFetchOptions {
  preferZh?: boolean
  pageTimeoutMs?: number
  captionTimeoutMs?: number
}

async function fetchText(url: string, timeoutMs: number): Promise<string | null> {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  try {
    const res = await fetch(url, { signal: controller.signal })
    if (!res.ok)
      return null
    return await res.text()
  }
  catch {
    return null
  }
  finally {
    clearTimeout(timer)
  }
}

async function fetchJson(url: string, timeoutMs: number): Promise<unknown | null> {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  try {
    const res = await fetch(url, {
      signal: controller.signal,
      headers: { Accept: 'application/json' },
    })
    if (!res.ok)
      return null
    return await res.json()
  }
  catch {
    return null
  }
  finally {
    clearTimeout(timer)
  }
}

function langScore(code: string, preferZh: boolean, manual: boolean): number {
  const c = code.toLowerCase()
  const m = manual ? 4 : 0
  if (preferZh) {
    if (c.startsWith('zh') || c.includes('chinese'))
      return 10 + m
    if (c === 'en' || c.includes('english'))
      return 5 + m
  }
  else {
    if (c === 'en' || c.includes('english'))
      return 10 + m
    if (c.startsWith('zh') || c.includes('chinese'))
      return 5 + m
  }
  return m
}

async function tryPipedInstance(
  base: string,
  videoId: string,
  opts: ProxyFetchOptions,
): Promise<ProxyTranscriptResult | null> {
  const pageMs = opts.pageTimeoutMs ?? 18_000
  const capMs = opts.captionTimeoutMs ?? 25_000
  const preferZh = opts.preferZh ?? true

  const data = await fetchJson(`${base}/streams/${videoId}`, pageMs) as {
    title?: string
    subtitles?: Array<{ url?: string, code?: string, autoGenerated?: boolean }>
  } | null
  if (!data?.subtitles?.length)
    return null

  const sub = [...data.subtitles].sort((a, b) => {
    const sa = langScore(a.code || '', preferZh, !a.autoGenerated)
    const sb = langScore(b.code || '', preferZh, !b.autoGenerated)
    return sb - sa
  })[0]
  if (!sub?.url)
    return null

  const raw = await fetchText(sub.url, capMs)
  if (!raw)
    return null
  const plain = subtitleBodyToPlain(raw)
  if (!plain.trim())
    return null

  return {
    videoTitle: data.title?.trim() || 'YouTube Video',
    transcript: plain,
    formats: buildTranscriptFormats(plain),
  }
}

async function tryInvidiousInstance(
  base: string,
  videoId: string,
  opts: ProxyFetchOptions,
): Promise<ProxyTranscriptResult | null> {
  const pageMs = opts.pageTimeoutMs ?? 18_000
  const capMs = opts.captionTimeoutMs ?? 25_000
  const preferZh = opts.preferZh ?? true

  const listRaw = await fetchText(`${base}/api/v1/captions/${videoId}`, pageMs)
  if (!listRaw)
    return null
  let list: Array<{ label: string, language_code?: string, languageCode?: string }>
  try {
    list = JSON.parse(listRaw) as typeof list
  }
  catch {
    return null
  }
  if (!Array.isArray(list) || !list.length)
    return null

  const meta = [...list].sort((a, b) => {
    const ca = a.language_code || a.languageCode || a.label
    const cb = b.language_code || b.languageCode || b.label
    return langScore(cb, preferZh, true) - langScore(ca, preferZh, true)
  })[0]
  if (!meta?.label)
    return null

  const subRaw = await fetchText(
    `${base}/api/v1/captions/${videoId}?label=${encodeURIComponent(meta.label)}`,
    capMs,
  )
  if (!subRaw)
    return null
  const plain = subtitleBodyToPlain(subRaw)
  if (!plain.trim())
    return null

  let title = 'YouTube Video'
  const videoRaw = await fetchText(`${base}/api/v1/videos/${videoId}`, pageMs)
  if (videoRaw) {
    try {
      const v = JSON.parse(videoRaw) as { title?: string }
      if (v.title?.trim())
        title = v.title.trim()
    }
    catch { /* ignore */ }
  }

  return {
    videoTitle: title,
    transcript: plain,
    formats: buildTranscriptFormats(plain),
  }
}

/** 并行尝试多个 Piped/Invidious 实例（仅适合服务器端，浏览器会因 CORS 失败） */
export async function fetchTranscriptViaProxies(
  url: string,
  opts: ProxyFetchOptions = {},
): Promise<ProxyTranscriptResult | null> {
  const videoId = extractVideoId(url)
  if (!videoId)
    return null

  const jobs = [
    ...PIPED_INSTANCES.map(base => tryPipedInstance(base, videoId, opts)),
    ...INVIDIOUS_INSTANCES.map(base => tryInvidiousInstance(base, videoId, opts)),
  ]

  const settled = await Promise.allSettled(jobs)
  for (const r of settled) {
    if (r.status === 'fulfilled' && r.value)
      return r.value
  }
  return null
}
